version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: url-shortener
    ports:
      - 8080:80
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: url_shortener
      DB_USERNAME: app
      DB_PASSWORD: password
      DOMIN: localhost:8080
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password